In [1]:
import warnings
from typing import List

import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
from autumn.core.inputs.database import get_input_db
from autumn.core.project import get_project
from autumn.settings import Region, Models
from autumn.core import inputs
from autumn.core.inputs.social_mixing.build_synthetic_matrices import build_synthetic_matrices
from autumn.core.utils.display import pretty_print
from autumn.core.inputs.tb_camau import queries
import pathlib
from autumn.model_features.curve.interpolate import build_static_sigmoidal_multicurve
from summer2.parameters.params import Function
import jax
import numpy as np

In [2]:
warnings.filterwarnings("ignore")
pd.options.plotting.backend = "plotly"

In [3]:
csv_path = pathlib.Path("camau.csv")

In [4]:
region = Region.CAMAU
model = Models.TBD2
p = get_project(model, region, reload=True)
baseline_params = p.param_set.baseline

In [5]:
iso3 = baseline_params['country']['iso3']
source_iso3 = baseline_params['age_mixing']['source_iso3']
age_adjust = baseline_params['age_mixing']['age_adjust']
age_string_map = {
    0: "0-4",
    5: "5-14",
    15: "15-34",
    35: "35-49",
    50: "50+",
}

## Population

In [6]:
modelled_age_groups = baseline_params["age_breakpoints"]
print(f"Modelled age groups are {modelled_age_groups}")

Modelled age groups are [0, 5, 15, 35, 50]


In [7]:
pop_df = pd.read_csv(csv_path)
pop_df = pop_df.set_index(['year'])
pop_df['population'].plot()

### Birth rate

In [8]:
birth_rates, years = inputs.get_crude_birth_rate("VNM")
birth_rates = [b / 1000.0 for b in birth_rates]  # Birth rates are provided / 1000 population
birth_rates_series = pd.Series(birth_rates, index=years)
br_fig= px.line(birth_rates_series)
br_fig.update_traces(mode='markers+lines')
br_fig.update_layout(
    title="Crude birth rate of Ca Mau",
    title_x=0.5,
    xaxis_title="Year",
    yaxis_title="Crude birth rate",
    showlegend=False,
)

### Death rate

In [9]:
#Query and visualize the crude birth rate from database
years, death_rates = queries.get_camau_death_rate()
death_rates = [b / 1000.0 for b in death_rates]  # Birth rates are provided / 1000 population
death_rates_series = pd.Series(death_rates, index=years)
dr_fig= px.line(death_rates_series)
dr_fig.update_traces(mode='markers+lines')
dr_fig.update_layout(
    title="Crude death rate of Ca Mau",
    title_x=0.5,
    xaxis_title="Year",
    yaxis_title="Crude death rate",
    showlegend=False,
)

### Mixing matrix

In [10]:
print(f"Target region: {region.upper()} ({iso3})")
print(f"Proxy country: {source_iso3}")
print("Always age-adjusted to target population")

Target region: CAMAU (VNM)
Proxy country: VNM
Always age-adjusted to target population


In [11]:
update_params = {
    'contact_rate': 0.009976641551950861,
    'infectious_seed': 166,
    'progression_multiplier': 0.314988113161106,
    'rr_infection_latent': 0.49076018816019046,
    'rr_infection_recovered': 0.24685066299673822,
    'start_population_size':232213.3052017466,
    'cdr_adjustment': 0.6013891618826954

}
params = baseline_params.update(update_params,calibration_format=True)
model_0  =  p.build_model(params.to_dict())
model_0.run(params.to_dict())
derived_df_0 = model_0.get_derived_outputs_df()

In [12]:
#get the step test object
res = model_0._get_step_test(params.to_dict(), 2000)
print(res.ts_graph_vals['age_mixing_matrix'])
# it is the "real" age_mixing matrix
px.imshow(res.ts_graph_vals['age_mixing_matrix'])

[[ 398.43289672  261.82020387  643.68286218  401.62199159  356.13449939]
 [ 165.78966683  881.63067677  532.84120554  550.75979227  285.62836724]
 [ 231.75164317  311.38983781  915.52884268  673.30894113  664.14577066]
 [ 141.94492435  310.88835505  786.13676958 1134.31076003  938.03403291]
 [  67.30073632  170.46333134  647.30153978 1018.81243422 1763.57657715]]


In [13]:
model_0.graph.draw()

In [14]:
fig2_1 = px.line(
    derived_df_0,
    x=derived_df_0.index,
    y="total_population",
)
fig2_2 = px.scatter(pop_df.reset_index(), x="year", y="population")
fig2_2.update_traces(marker=dict(color="red"))
fig2_3 = go.Figure(
    data=fig2_1.data + fig2_2.data,
)
fig2_3.update_layout(
    title="Modelled vs Data", title_x=0.5, xaxis_title="Year", yaxis_title="Population"
)
fig2_3.show()

In [15]:
derived_df_0.incidence.plot()

In [16]:
derived_df_0.percentage_latent.plot()

In [17]:
#from autumn.model_features.curve.interpolate import build_static_sigmoidal_multicurve
# tfunc = build_static_sigmoidal_multicurve([float(k) for k in params['time_variant_tb_screening_rate'].keys()], [float(v) for v in params['time_variant_tb_screening_rate'].values()])
# np.array(jax.numpy.asarray([tfunc(t) * 0.8 for t in model_0.times]))
# derived_df_0.sigmoid_param

In [18]:
derived_df_0.notifications.plot()